/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hbo_proyecto;

/**
 *
 * @author MARLON
 */
public class InterfaceVelma extends javax.swing.JPanel {

    /**
     * Creates new form InterfaceVelma
     */
    public InterfaceVelma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        menosIntro = new javax.swing.JButton();
        masIntro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menosCredito = new javax.swing.JButton();
        credito = new javax.swing.JLabel();
        masCredito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        menosInicio = new javax.swing.JButton();
        inicio = new javax.swing.JLabel();
        masInicio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        menosCierre = new javax.swing.JButton();
        cierre = new javax.swing.JLabel();
        masCierre = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        menosPlot = new javax.swing.JButton();
        plot = new javax.swing.JLabel();
        masPlot = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        menosEnsamblador = new javax.swing.JButton();
        ensamblador = new javax.swing.JLabel();
        masEnsamblador = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        entrega = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        epNormal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        epPlot = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        entregados = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ganancias = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        actividadDirector = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        actividadPM = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setText("Serie");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, -1));

        jLabel1.setText("Intro:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        intro.setText("0");
        jPanel1.add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 30, -1));

        menosIntro.setText("-");
        menosIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosIntroActionPerformed(evt);
            }
        });
        jPanel1.add(menosIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        masIntro.setText("+");
        jPanel1.add(masIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setText("Credito");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        menosCredito.setText("-");
        menosCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(menosCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        credito.setText("0");
        jPanel1.add(credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 30, -1));

        masCredito.setText("+");
        jPanel1.add(masCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel3.setText("Inicio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        menosInicio.setText("-");
        menosInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosInicioActionPerformed(evt);
            }
        });
        jPanel1.add(menosInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        inicio.setText("0");
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 30, -1));

        masInicio.setText("+");
        jPanel1.add(masInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Cierre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        menosCierre.setText("-");
        menosCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosCierreActionPerformed(evt);
            }
        });
        jPanel1.add(menosCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        cierre.setText("0");
        jPanel1.add(cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 30, -1));

        masCierre.setText("+");
        jPanel1.add(masCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel5.setText("Plot");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        menosPlot.setText("-");
        menosPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosPlotActionPerformed(evt);
            }
        });
        jPanel1.add(menosPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        plot.setText("0");
        jPanel1.add(plot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 30, -1));

        masPlot.setText("+");
        jPanel1.add(masPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setText("Ensamblador");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        menosEnsamblador.setText("-");
        menosEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(menosEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        ensamblador.setText("0");
        jPanel1.add(ensamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, -1));

        masEnsamblador.setText("+");
        jPanel1.add(masEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel7.setText("dias para entrega");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        entrega.setText("0");
        jPanel1.add(entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 40, -1));

        jLabel8.setText("episodios listos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel9.setText("Normales");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        epNormal.setText("0");
        jPanel1.add(epNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 40, -1));

        jLabel11.setText("Con plot");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        epPlot.setText("0");
        jPanel1.add(epPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 30, -1));

        jLabel10.setText("Episodios lanzados:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        entregados.setText("0");
        jPanel1.add(entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 40, -1));

        jLabel13.setText("(lote anterior)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel14.setText("Ganancias totales; $");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        ganancias.setText("0");
        jPanel1.add(ganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 80, -1));

        jLabel12.setText("Director:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        actividadDirector.setText("init");
        jPanel1.add(actividadDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, -1));

        jLabel15.setText("PM:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        actividadPM.setText("init");
        jPanel1.add(actividadPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, -1));

        jLabel16.setText("Faltas:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel17.setText("0");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, -1));

        jLabel18.setText("Salario PM: $");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel19.setText("0");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 110, -1));

        jLabel20.setText("Salario mensual: $");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel21.setText("0");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void menosIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosIntroActionPerformed

    private void menosCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCreditoActionPerformed

    private void menosInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosInicioActionPerformed

    private void menosCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosCierreActionPerformed

    private void menosPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosPlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosPlotActionPerformed

    private void menosEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEnsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEnsambladorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel actividadDirector;
    public static javax.swing.JLabel actividadPM;
    public static javax.swing.JLabel cierre;
    public static javax.swing.JLabel credito;
    public static javax.swing.JLabel ensamblador;
    public static javax.swing.JLabel entrega;
    public static javax.swing.JLabel entregados;
    public static javax.swing.JLabel epNormal;
    public static javax.swing.JLabel epPlot;
    public static javax.swing.JLabel ganancias;
    public static javax.swing.JLabel inicio;
    public static javax.swing.JLabel intro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton masCierre;
    public static javax.swing.JButton masCredito;
    public static javax.swing.JButton masEnsamblador;
    public static javax.swing.JButton masInicio;
    public static javax.swing.JButton masIntro;
    public static javax.swing.JButton masPlot;
    public static javax.swing.JButton menosCierre;
    public static javax.swing.JButton menosCredito;
    public static javax.swing.JButton menosEnsamblador;
    public static javax.swing.JButton menosInicio;
    public static javax.swing.JButton menosIntro;
    public static javax.swing.JButton menosPlot;
    public static javax.swing.JLabel plot;
    public static javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
