/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hbo_proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class Menu extends javax.swing.JFrame {

    InterfaceGOT int1;
    //InterfaceVelma int2;
    int Duradia;
    int Diaslanzamiento;
    int pIntro;
    int pCredito;
    int PInicio;
    int pCierre;
    int pPlot;
    int Ensamblador;
    
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        impo = new javax.swing.JButton();
        GOT = new javax.swing.JButton();
        velma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        impo.setText("Velma");
        impo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impoActionPerformed(evt);
            }
        });
        jPanel1.add(impo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, -1));

        GOT.setText("GOT");
        GOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOTActionPerformed(evt);
            }
        });
        jPanel1.add(GOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 290, 130, -1));

        velma.setText("Velma");
        velma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velmaActionPerformed(evt);
            }
        });
        jPanel1.add(velma, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 290, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void impoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impoActionPerformed
        String line;
        String txt = "";

        JFileChooser archivo = new JFileChooser();
        int seleccion;
        seleccion = archivo.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            String nameArchivo = archivo.getSelectedFile().getAbsolutePath();
            File archivoTxt = new File(nameArchivo);
            
            try{
                FileReader fr = new FileReader(archivoTxt);
                if (fr.ready()){
                    BufferedReader br = new BufferedReader(fr);
                     while ((line = br.readLine()) != ";"){
                        if (!line.isEmpty()) {
                            txt += line + "\n";
                        }
                     }
                     if (!txt.isEmpty()) {
                         String[] txtSplit = txt.split("\n");
                         for (int i = 0; i < txtSplit.length; i++){
                             String[] lectura = txt.split(": ");
                             if(lectura[0] == "Duracion de 1 dia en segundos"){
                                String duracionDia = lectura[1];
                                this.Duradia = Integer.parseInt(duracionDia);
                                
                             }else if(lectura[0] == "Cantidad de dias entre lanzamientos"){
                                String DiasLanzamiento = lectura[1];
                                this.Diaslanzamiento = Integer.parseInt(DiasLanzamiento);
             
                             }else if(lectura[0] == "Cantidad de productores de intro"){
                                String pIntro = lectura[1];
                                this.pIntro = Integer.parseInt(pIntro);
                                
                             }else if(lectura[0] == "Cantidad de productores de credito"){
                                 String pCredito = lectura[1];
                                 this.pCredito = Integer.parseInt(pCredito);
                                 
                             }else if(lectura[0] == "Cantidad de productores de inicio"){
                                 String pInicio = lectura[1];
                                 this.PInicio = Integer.parseInt(pInicio);
                                 
                             }else if(lectura[0] == "Cantidad de productores de cierre"){
                                 String pCierre = lectura[1];
                                 this.pCierre = Integer.parseInt(pCierre);
                                 
                             }else if(lectura[0] == "Cantidad de productores de plot twist"){
                                 String pPlot = lectura[1];
                                 this.pPlot = Integer.parseInt(pPlot);
                                 
                             }else if(lectura[0] == "Cantidad inicial de ensambladores"){
                                 String Ensamblador = lectura[1];
                                 this.Ensamblador = Integer.parseInt(Ensamblador);
                             }
                        }
                        br.close();
                        JOptionPane.showMessageDialog(null, "Se ha cargado el archivo correctamente");
                     }
                }else{
                    JOptionPane.showMessageDialog(null, "El archivo no esta listo para ser leido");
                    
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Archivo no compatible");
            }
        }
    }//GEN-LAST:event_impoActionPerformed
      
    private void GOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOTActionPerformed
        // TODO add your handling code here:
        
        int1 = new InterfaceGOT("GOT");
        int1.setVisible(true);
        
    }//GEN-LAST:event_GOTActionPerformed

    private void velmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velmaActionPerformed
        // TODO add your handling code here:
        int1 = new InterfaceGOT("Velma");
        int1.setVisible(true);
    }//GEN-LAST:event_velmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GOT;
    private javax.swing.JButton impo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton velma;
    // End of variables declaration//GEN-END:variables
}
